using System;

namespace Invoca.Model
{
    public class Response
    {
        public string TransactionId { get; set; }
        public string CorrectsTransactionId { get; set; }
        public string TransactionType { get; set; }
        public string OriginalOrderId { get; set; }
        public string AdvertiserCampaignId { get; set; }
        public string AdvertiserCampaignIdFromNetwork { get; set; }
        public string AdvertiserCampaignName { get; set; }
        public string AffiliateId { get; set; }
        public string AffiliateIdFromNetwork { get; set; }
        public string AffiliateName { get; set; }
        public string AffiliateCommissionsRanking { get; set; }
        public string AffiliateCallVolumeRanking { get; set; }
        public string AffiliateConversionRateRanking { get; set; }
        public string MediaType { get; set; }
        public string CallSourceDescription { get; set; }
        public string SyndicatedIdent { get; set; }
        public string PromoLineDescription { get; set; }
        public string VirtualLineId { get; set; }
        public string CallResultDescriptionDetailManagedAdvertiser { get; set; }
        public string AdvertiserPayinLocalized { get; set; }
        public string MatchingAdvertiserPayinPolicies { get; set; }
        public string PayinConditions { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string QualifiedRegions { get; set; }
        public string RepeatCallingPhoneNumber { get; set; }
        public string CallingPhoneNumber { get; set; }
        public string Mobile { get; set; }
        public int Duration { get; set; }
        public int ConnectDuration { get; set; }
        public int IvrDuration { get; set; }
        public string Keypresses { get; set; }
        public string Keypress1 { get; set; }
        public string Keypress2 { get; set; }
        public string Keypress3 { get; set; }
        public string Keypress4 { get; set; }
        public string DynamicNumberPoolReferrerSearchEngine { get; set; }
        public string DynamicNumberPoolReferrerSearchKeywords { get; set; }
        public string DynamicNumberPoolReferrerSearchKeywordsId { get; set; }
        public string DynamicNumberPoolReferrerAd { get; set; }
        public string DynamicNumberPoolReferrerAdId { get; set; }
        public string DynamicNumberPoolReferrerAdGroup { get; set; }
        public string DynamicNumberPoolReferrerAdGroupId { get; set; }
        public string DynamicNumberPoolReferrerReferrerCampaign { get; set; }
        public string DynamicNumberPoolReferrerReferrerCampaignId { get; set; }
        public string DynamicNumberPoolReferrerKeywordMatchType { get; set; }
        public string DynamicNumberPoolReferrerParam1Name { get; set; }
        public string DynamicNumberPoolReferrerParam1Value { get; set; }
        public string DynamicNumberPoolReferrerParam2Name { get; set; }
        public string DynamicNumberPoolReferrerParam2Value { get; set; }
        public string DynamicNumberPoolReferrerParam3Name { get; set; }
        public string DynamicNumberPoolReferrerParam3Value { get; set; }
        public string DynamicNumberPoolReferrerParam4Name { get; set; }
        public string DynamicNumberPoolReferrerParam4Value { get; set; }
        public string DynamicNumberPoolReferrerParam5Name { get; set; }
        public string DynamicNumberPoolReferrerParam5Value { get; set; }
        public string DynamicNumberPoolReferrerParam6Name { get; set; }
        public string DynamicNumberPoolReferrerParam6Value { get; set; }
        public string DynamicNumberPoolReferrerParam7Name { get; set; }
        public string DynamicNumberPoolReferrerParam7Value { get; set; }
        public string DynamicNumberPoolReferrerParam8Name { get; set; }
        public string DynamicNumberPoolReferrerParam8Value { get; set; }
        public string DynamicNumberPoolReferrerParam9Name { get; set; }
        public string DynamicNumberPoolReferrerParam9Value { get; set; }
        public string DynamicNumberPoolReferrerParam10Name { get; set; }
        public string DynamicNumberPoolReferrerParam10Value { get; set; }
        public string DynamicNumberPoolReferrerSearchType { get; set; }
        public string DynamicNumberPoolPoolType { get; set; }
        public int DynamicNumberPoolId { get; set; }
        public string StartTimeLocal { get; set; }
        public DateTime StartTimeXml { get; set; }
        public string StartTimeUtc { get; set; }
        public string StartTimeNetworkTimezone { get; set; }
        public DateTime StartTimeNetworkTimezoneXml { get; set; }
        public string Recording { get; set; }
        public string CorrectedAt { get; set; }
        public int OptInSMS { get; set; }
        public string CompleteCallId { get; set; }
        public string TransferFromType { get; set; }
        public string Notes { get; set; }
        public string VerifiedZip { get; set; }
        public string SignalName { get; set; }
        public string SignalDescription { get; set; }
        public string SignalPartnerUniqueId { get; set; }
        public string SignalOccurredAt { get; set; }
        public string SignalSource { get; set; }
        public string SignalValue { get; set; }
        public string SignalCustomParameter1 { get; set; }
        public string SignalCustomParameter2 { get; set; }
        public string SignalCustomParameter3 { get; set; }
        public string EmailAddress { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string OrderCity { get; set; }
        public string StateOrProvince { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string HomePhoneNumber { get; set; }
        public string CellPhoneNumber { get; set; }
        public string SkuList { get; set; }
        public string QuantityList { get; set; }
        public string SaleAmount { get; set; }
        public string CallCenterCallId { get; set; }
        public string DestinationPhoneNumber { get; set; }
    }
}
